"""
CI/CD Integration Module

Provides helpers and templates for integrating security testing into CI/CD pipelines.

Supported providers:
    - GitHub Actions
    - GitLab CI
    - Jenkins

Usage:
    from dspy_guardrails.testing.ci import generate_workflow

    # Generate GitHub Actions workflow
    workflow = generate_workflow(
        provider="github",
        config_path="promptfoo.yaml",
        threshold=0.8,
    )

    # Write to file
    with open(".github/workflows/security-scan.yml", "w") as f:
        f.write(workflow)
"""

from .github_actions import (
    GitHubActionsConfig,
    generate_github_workflow,
)

__all__ = [
    "generate_workflow",
    "generate_github_workflow",
    "GitHubActionsConfig",
]


def generate_workflow(
    provider: str = "github",
    config_path: str = "promptfoo.yaml",
    threshold: float = 0.8,
    **kwargs,
) -> str:
    """Generate CI/CD workflow configuration.

    Args:
        provider: CI provider (github, gitlab, jenkins)
        config_path: Path to promptfoo config file
        threshold: Block rate threshold for pass/fail
        **kwargs: Provider-specific options

    Returns:
        Workflow configuration string

    Raises:
        ValueError: If provider not supported
    """
    if provider == "github":
        return generate_github_workflow(
            config_path=config_path,
            threshold=threshold,
            **kwargs,
        )
    elif provider == "gitlab":
        return _generate_gitlab_workflow(
            config_path=config_path,
            threshold=threshold,
            **kwargs,
        )
    elif provider == "jenkins":
        return _generate_jenkins_workflow(
            config_path=config_path,
            threshold=threshold,
            **kwargs,
        )
    else:
        raise ValueError(f"Unsupported CI provider: {provider}")


def _generate_gitlab_workflow(
    config_path: str = "promptfoo.yaml",
    threshold: float = 0.8,
    **kwargs,
) -> str:
    """Generate GitLab CI workflow."""
    return f"""# GitLab CI Security Scan
# Generated by dspy-guardrails

stages:
  - security

security-scan:
  stage: security
  image: python:3.11-slim
  before_script:
    - pip install dspy-guardrails
  script:
    - dspy-guardrails redteam run --config {config_path} --threshold {threshold} -f json -o ./results
  artifacts:
    paths:
      - results/
    reports:
      junit: results/junit.xml
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
"""


def _generate_jenkins_workflow(
    config_path: str = "promptfoo.yaml",
    threshold: float = 0.8,
    **kwargs,
) -> str:
    """Generate Jenkins pipeline."""
    return f"""// Jenkinsfile for AI Security Scan
// Generated by dspy-guardrails

pipeline {{
    agent any

    stages {{
        stage('Setup') {{
            steps {{
                sh 'pip install dspy-guardrails'
            }}
        }}

        stage('Security Scan') {{
            steps {{
                sh 'dspy-guardrails redteam run --config {config_path} --threshold {threshold} -f json -o ./results'
            }}
        }}

        stage('Check Results') {{
            steps {{
                sh 'dspy-guardrails ci check --results results/results.json --threshold {threshold}'
            }}
        }}
    }}

    post {{
        always {{
            archiveArtifacts artifacts: 'results/**', allowEmptyArchive: true
        }}
        failure {{
            echo 'Security scan failed!'
        }}
    }}
}}
"""
