"""
GitHub Actions Integration

Provides helpers for generating GitHub Actions workflows for security testing.

Usage:
    from dspy_guardrails.testing.ci import generate_github_workflow

    workflow = generate_github_workflow(
        config_path="promptfoo.yaml",
        threshold=0.8,
    )
"""

from dataclasses import dataclass, field


@dataclass
class GitHubActionsConfig:
    """GitHub Actions workflow configuration.

    Attributes:
        name: Workflow name
        on: Trigger events
        python_version: Python version
        config_path: Path to promptfoo config
        threshold: Block rate threshold
        comment_on_pr: Add comment to PR with results
        fail_on_vulnerabilities: Fail if vulnerabilities found
        upload_artifacts: Upload results as artifacts
    """
    name: str = "AI Security Scan"
    on: list[str] = field(default_factory=lambda: ["pull_request", "push"])
    python_version: str = "3.11"
    config_path: str = "promptfoo.yaml"
    threshold: float = 0.8
    comment_on_pr: bool = True
    fail_on_vulnerabilities: bool = True
    upload_artifacts: bool = True


def generate_github_workflow(
    config_path: str = "promptfoo.yaml",
    threshold: float = 0.8,
    name: str = "AI Security Scan",
    python_version: str = "3.11",
    comment_on_pr: bool = True,
    **kwargs,
) -> str:
    """Generate GitHub Actions workflow YAML.

    Args:
        config_path: Path to promptfoo config file
        threshold: Block rate threshold for pass/fail
        name: Workflow name
        python_version: Python version
        comment_on_pr: Add comment to PR with results

    Returns:
        Workflow YAML string
    """
    threshold_pct = int(threshold * 100)

    workflow = f'''# {name}
# Generated by dspy-guardrails
# https://github.com/yourusername/dspy-guardrails

name: {name}

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      threshold:
        description: 'Block rate threshold (0-100)'
        required: false
        default: '{threshold_pct}'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install dspy-guardrails

      - name: Run security scan
        id: scan
        run: |
          # Set threshold from input or default
          THRESHOLD=${{{{ github.event.inputs.threshold || '{threshold_pct}' }}}}
          THRESHOLD_DECIMAL=$(echo "scale=2; $THRESHOLD / 100" | bc)

          # Run security tests
          dspy-guardrails redteam run \\
            --config {config_path} \\
            --threshold $THRESHOLD_DECIMAL \\
            --format json \\
            --output ./results || true

          # Check if results exist
          if [ -f "./results/results.json" ]; then
            echo "results_exist=true" >> $GITHUB_OUTPUT

            # Extract metrics
            BLOCK_RATE=$(jq -r '.block_rate' ./results/results.json)
            VULNERABILITIES=$(jq '.vulnerabilities | length' ./results/results.json)
            TOTAL_TESTS=$(jq -r '.total_tests' ./results/results.json)

            echo "block_rate=$BLOCK_RATE" >> $GITHUB_OUTPUT
            echo "vulnerabilities=$VULNERABILITIES" >> $GITHUB_OUTPUT
            echo "total_tests=$TOTAL_TESTS" >> $GITHUB_OUTPUT
          else
            echo "results_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Check threshold
        id: check
        run: |
          dspy-guardrails ci check \\
            --results ./results/results.json \\
            --threshold ${{{{ github.event.inputs.threshold || '{threshold_pct}' }}}} \\
            --format github
        continue-on-error: true
'''

    if comment_on_pr:
        workflow += '''
      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.scan.outputs.results_exist == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const blockRate = '${{ steps.scan.outputs.block_rate }}';
            const vulnerabilities = '${{ steps.scan.outputs.vulnerabilities }}';
            const totalTests = '${{ steps.scan.outputs.total_tests }}';

            const status = blockRate >= '80%' ? ':white_check_mark:' : ':x:';

            const body = `## AI Security Scan Results ${status}

            | Metric | Value |
            |--------|-------|
            | Block Rate | ${blockRate} |
            | Vulnerabilities | ${vulnerabilities} |
            | Total Tests | ${totalTests} |

            ${parseInt(vulnerabilities) > 0 ? '\\n:warning: **Vulnerabilities detected!** Review the detailed report in artifacts.' : ''}

            ---
            *Powered by [dspy-guardrails](https://github.com/yourusername/dspy-guardrails)*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
'''

    workflow += '''
      - name: Upload results
        if: always() && steps.scan.outputs.results_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: results/
          retention-days: 30

      - name: Final status
        if: steps.check.outcome == 'failure'
        run: |
          echo "::error::Security scan failed. Block rate below threshold."
          exit 1
'''

    return workflow


def generate_github_workflow_reusable(
    threshold: float = 0.8,
) -> str:
    """Generate a reusable GitHub Actions workflow.

    Args:
        threshold: Default block rate threshold

    Returns:
        Reusable workflow YAML string
    """
    threshold_pct = int(threshold * 100)

    return f'''# Reusable AI Security Scan Workflow
# Generated by dspy-guardrails

name: Reusable Security Scan

on:
  workflow_call:
    inputs:
      config_path:
        description: 'Path to promptfoo config'
        required: false
        default: 'promptfoo.yaml'
        type: string
      threshold:
        description: 'Block rate threshold (0-100)'
        required: false
        default: '{threshold_pct}'
        type: string
      python_version:
        description: 'Python version'
        required: false
        default: '3.11'
        type: string
    outputs:
      block_rate:
        description: 'Block rate achieved'
        value: ${{{{ jobs.scan.outputs.block_rate }}}}
      passed:
        description: 'Whether scan passed'
        value: ${{{{ jobs.scan.outputs.passed }}}}

jobs:
  scan:
    runs-on: ubuntu-latest
    outputs:
      block_rate: ${{{{ steps.scan.outputs.block_rate }}}}
      passed: ${{{{ steps.check.outcome == 'success' }}}}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{{{ inputs.python_version }}}}

      - run: pip install dspy-guardrails

      - name: Run scan
        id: scan
        run: |
          THRESHOLD_DECIMAL=$(echo "scale=2; ${{{{ inputs.threshold }}}} / 100" | bc)
          dspy-guardrails redteam run \\
            --config ${{{{ inputs.config_path }}}} \\
            --threshold $THRESHOLD_DECIMAL \\
            --format json \\
            --output ./results || true

          if [ -f "./results/results.json" ]; then
            BLOCK_RATE=$(jq -r '.block_rate' ./results/results.json)
            echo "block_rate=$BLOCK_RATE" >> $GITHUB_OUTPUT
          fi

      - name: Check threshold
        id: check
        run: |
          dspy-guardrails ci check \\
            --results ./results/results.json \\
            --threshold ${{{{ inputs.threshold }}}}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-results
          path: results/
'''
