"""
Enhanced CLI for Promptfoo-style Security Testing

Provides Click-based CLI commands for:
    - redteam init: Initialize configuration
    - redteam run: Run security tests
    - ci generate: Generate CI/CD workflows
    - ci check: Check test results against thresholds

Usage:
    # Initialize with preset
    $ dspy-guardrails redteam init --preset owasp:llm -o promptfoo.yaml

    # Run tests
    $ dspy-guardrails redteam run --config promptfoo.yaml
    $ dspy-guardrails redteam run --preset quick-scan --target http://localhost:9000

    # CI/CD
    $ dspy-guardrails ci generate --provider github
    $ dspy-guardrails ci check --results results.json --threshold 80
"""

import json
import sys
from html import escape
from pathlib import Path
from urllib.parse import urlparse

import click

from .cache import LLMCallCache
from .config import PromptfooConfig, TargetConfig, normalize_strategy_id
from .plugins import list_plugins as list_available_plugins
from .presets import list_presets as list_available_presets
from .runner import ConcurrentTestRunner, RunProgress

# =============================================================================
# Internal Helpers
# =============================================================================


def _create_http_target(target_config: TargetConfig):
    """Create a real HTTP target adapter from target configuration."""
    from ..platform.targets.http import HTTPTarget

    parsed = urlparse(target_config.url)
    if not parsed.scheme or not parsed.netloc:
        raise ValueError(
            f"Invalid HTTP target URL: {target_config.url!r}. "
            "Expected format like http://host:port/path"
        )

    base_url = f"{parsed.scheme}://{parsed.netloc}"
    endpoint = parsed.path or "/chat"
    if parsed.query:
        endpoint = f"{endpoint}?{parsed.query}"

    options = target_config.options or {}
    return HTTPTarget(
        base_url=base_url,
        endpoint=endpoint,
        method=target_config.method,
        headers=target_config.headers,
        timeout=target_config.timeout,
        response_key=options.get("response_key", "response"),
        blocked_key=options.get("blocked_key", "blocked"),
        block_reason_key=options.get("block_reason_key", "block_reason"),
        session_enabled=options.get("session_enabled", True),
    )


def _save_html_report(summary, output_path: Path) -> None:
    """Generate a lightweight HTML report for promptfoo-style runs."""
    vulnerabilities = summary.vulnerabilities
    rows = []
    for vuln in vulnerabilities[:50]:
        severity = (
            vuln.payload.severity.value
            if hasattr(vuln.payload.severity, "value")
            else str(vuln.payload.severity)
        )
        prompt = (
            vuln.payload.prompt[:140] + "..."
            if len(vuln.payload.prompt) > 140
            else vuln.payload.prompt
        )
        severity_text = escape(str(severity))
        payload_id = escape(str(vuln.payload.id))
        technique = escape(str(vuln.payload.technique))
        prompt_text = escape(str(prompt))
        rows.append(
            f"<tr><td>{severity_text}</td><td>{payload_id}</td>"
            f"<td>{technique}</td><td>{prompt_text}</td></tr>"
        )

    fallback_row = "<tr><td colspan='4'>No vulnerabilities found</td></tr>"
    table_rows = "".join(rows) if rows else fallback_row
    table_html = (
        "<table><thead><tr><th>Severity</th><th>ID</th><th>Technique</th><th>Payload</th></tr></thead>"
        f"<tbody>{table_rows}</tbody></table>"
    )

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>dspyGuardrails Security Report</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 24px; color: #111827; }}
    h1 {{ margin-bottom: 8px; }}
    .grid {{ display: grid; grid-template-columns: repeat(3, minmax(160px, 1fr)); gap: 12px; max-width: 900px; }}
    .card {{ border: 1px solid #d1d5db; border-radius: 8px; padding: 12px; background: #f9fafb; }}
    .label {{ color: #6b7280; font-size: 12px; }}
    .value {{ font-size: 24px; font-weight: 700; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
    th, td {{ border: 1px solid #e5e7eb; padding: 8px; text-align: left; vertical-align: top; font-size: 13px; }}
    th {{ background: #f3f4f6; }}
  </style>
</head>
<body>
  <h1>dspyGuardrails Security Report</h1>
  <p>Generated by promptfoo-style runner</p>
  <div class="grid">
    <div class="card"><div class="label">Total Tests</div><div class="value">{summary.total_tests}</div></div>
    <div class="card"><div class="label">Block Rate</div><div class="value">{summary.block_rate:.1%}</div></div>
    <div class="card"><div class="label">Attack Success Rate</div><div class="value">{summary.attack_success_rate:.1%}</div></div>
    <div class="card"><div class="label">Blocked</div><div class="value">{summary.blocked_attacks}</div></div>
    <div class="card"><div class="label">Bypassed</div><div class="value">{summary.successful_attacks}</div></div>
    <div class="card"><div class="label">Errors</div><div class="value">{summary.errors}</div></div>
  </div>
  <h2>Vulnerabilities</h2>
  {table_html}
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)


def _coerce_non_strict_config(test_config: PromptfooConfig) -> None:
    """Best-effort normalization when strict validation is disabled."""
    from ..redteam.strategies import list_strategies
    from .plugins import get_plugin

    allowed_severities = {"low", "medium", "high", "critical"}
    runtime_strategies = set(list_strategies())

    sanitized_plugins = []
    for plugin in test_config.plugins:
        plugin_id = plugin.id if isinstance(plugin.id, str) else ""
        plugin_id = plugin_id.strip()
        if not plugin_id:
            click.echo("Warning: skipping plugin with empty id", err=True)
            continue

        try:
            get_plugin(plugin_id)
        except ValueError:
            click.echo(f"Warning: skipping unknown plugin '{plugin_id}'", err=True)
            continue

        try:
            num_tests = int(plugin.numTests)
        except (TypeError, ValueError):
            click.echo(
                f"Warning: plugin '{plugin_id}' has invalid numTests={plugin.numTests!r}, using 10",
                err=True,
            )
            num_tests = 10
        if num_tests <= 0:
            click.echo(
                f"Warning: plugin '{plugin_id}' has numTests={num_tests}, using 10",
                err=True,
            )
            num_tests = 10
        plugin.numTests = num_tests

        severity = str(plugin.severity).strip().lower()
        if severity not in allowed_severities:
            click.echo(
                f"Warning: plugin '{plugin_id}' has invalid severity={plugin.severity!r}, using 'medium'",
                err=True,
            )
            severity = "medium"
        plugin.severity = severity
        plugin.id = plugin_id
        sanitized_plugins.append(plugin)
    test_config.plugins = sanitized_plugins

    sanitized_strategies = []
    for strategy in test_config.strategies:
        strategy_id = strategy.id if isinstance(strategy.id, str) else ""
        strategy_id = strategy_id.strip().lower()
        if not strategy_id:
            click.echo("Warning: skipping strategy with empty id", err=True)
            continue

        normalized_strategy_id = normalize_strategy_id(strategy_id)
        if normalized_strategy_id in {"basic", "default"}:
            continue
        if normalized_strategy_id not in runtime_strategies:
            click.echo(
                f"Warning: skipping unknown strategy '{strategy.id}'",
                err=True,
            )
            continue

        strategy.id = normalized_strategy_id
        if strategy.options is None:
            strategy.options = {}
        elif not isinstance(strategy.options, dict):
            click.echo(
                f"Warning: strategy '{strategy.id}' options must be a dict, using empty options",
                err=True,
            )
            strategy.options = {}
        sanitized_strategies.append(strategy)
    test_config.strategies = sanitized_strategies

    if test_config.maxWorkers <= 0:
        click.echo(
            f"Warning: invalid maxWorkers={test_config.maxWorkers}, using 1",
            err=True,
        )
        test_config.maxWorkers = 1

    sanitized_thresholds = {}
    for key, value in test_config.thresholds.items():
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            click.echo(
                f"Warning: ignoring non-numeric threshold '{key}'={value!r}",
                err=True,
            )
            continue
        if not 0.0 <= numeric <= 1.0:
            click.echo(
                f"Warning: ignoring out-of-range threshold '{key}'={numeric}",
                err=True,
            )
            continue
        sanitized_thresholds[key] = numeric
    test_config.thresholds = sanitized_thresholds


# =============================================================================
# Red Team Command Group
# =============================================================================

@click.group()
def redteam():
    """Red team security testing commands.

    Run security tests against AI systems using promptfoo-style configuration.
    """
    pass


@redteam.command()
@click.option(
    "--preset",
    "-p",
    default="quick-scan",
    help="Preset to use (owasp:llm, mitre:atlas, quick-scan)",
)
@click.option(
    "--output",
    "-o",
    default="promptfoo.yaml",
    type=click.Path(),
    help="Output configuration file path",
)
@click.option(
    "--target",
    "-t",
    default="",
    help="Target URL or guardrail name",
)
@click.option(
    "--list-presets",
    is_flag=True,
    help="List available presets",
)
@click.option(
    "--list-plugins",
    is_flag=True,
    help="List available plugins",
)
def init(preset: str, output: str, target: str, list_presets: bool, list_plugins: bool):
    """Initialize a security test configuration.

    Creates a promptfoo-style YAML configuration file based on the selected preset.

    \b
    Examples:
        dspy-guardrails redteam init --preset owasp:llm -o security.yaml
        dspy-guardrails redteam init --preset quick-scan --target http://localhost:9000
        dspy-guardrails redteam init --list-presets
    """
    # List presets
    if list_presets:
        click.echo("Available presets:\n")
        for preset_id, info in list_available_presets().items():
            click.echo(f"  {preset_id}")
            click.echo(f"    {info['description']}")
            click.echo(f"    Plugins: {info['plugin_count']}, Strategies: {info['strategy_count']}")
            click.echo()
        return

    # List plugins
    if list_plugins:
        click.echo("Available plugins:\n")
        for plugin_id, info in list_available_plugins().items():
            owasp = f" (OWASP: {info['owasp']})" if info.get('owasp') else ""
            click.echo(f"  {plugin_id}{owasp}")
            click.echo(f"    {info['description']}")
            click.echo()
        return

    try:
        # Create configuration from preset
        config = PromptfooConfig.from_preset(preset)

        # Add target if provided
        if target:
            config.targets = [TargetConfig.from_dict(target)]

        # Save configuration
        output_path = Path(output)
        config.save(output_path)

        click.echo(f"Configuration created: {output_path}")
        click.echo(f"  Preset: {preset}")
        click.echo(f"  Plugins: {len(config.plugins)}")
        click.echo(f"  Strategies: {len(config.strategies)}")

        if config.targets:
            click.echo(f"  Target: {config.targets[0].to_target_string()}")

        click.echo(f"\nRun tests with: dspy-guardrails redteam run --config {output_path}")

    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


@redteam.command()
@click.option(
    "--config",
    "-c",
    type=click.Path(exists=False),
    help="Configuration file path",
)
@click.option(
    "--preset",
    "-p",
    help="Use preset instead of config file",
)
@click.option(
    "--target",
    "-t",
    help="Target override (URL or guardrail:name)",
)
@click.option(
    "--output",
    "-o",
    default="./results",
    type=click.Path(),
    help="Output directory for results",
)
@click.option(
    "--format",
    "-f",
    "output_format",
    multiple=True,
    type=click.Choice(["console", "json", "html"]),
    default=["console"],
    help="Output format(s)",
)
@click.option(
    "--cache/--no-cache",
    default=True,
    help="Enable/disable LLM call caching",
)
@click.option(
    "--parallel/--no-parallel",
    default=True,
    help="Enable/disable parallel execution",
)
@click.option(
    "--workers",
    "-w",
    default=5,
    type=int,
    help="Number of parallel workers",
)
@click.option(
    "--threshold",
    default=None,
    type=float,
    help="Block rate threshold for pass/fail (0.0-1.0). Defaults to config.thresholds.block_rate or 0.8",
)
@click.option(
    "--strict/--no-strict",
    default=True,
    help="Fail fast on unknown plugins/strategies in config",
)
@click.option(
    "--verbose",
    "-v",
    is_flag=True,
    help="Verbose output",
)
def run(
    config: str | None,
    preset: str | None,
    target: str | None,
    output: str,
    output_format: tuple,
    cache: bool,
    parallel: bool,
    workers: int,
    threshold: float | None,
    strict: bool,
    verbose: bool,
):
    """Run security tests against a target.

    \b
    Examples:
        dspy-guardrails redteam run --config promptfoo.yaml
        dspy-guardrails redteam run --preset quick-scan --target http://localhost:9000
        dspy-guardrails redteam run -c security.yaml --threshold 0.9 -f json
    """
    # Load configuration
    try:
        if preset:
            test_config = PromptfooConfig.from_preset(preset, validate=strict)
        elif config:
            test_config = PromptfooConfig.from_yaml(config, validate=strict)
        else:
            click.echo("Error: Either --config or --preset is required", err=True)
            sys.exit(1)

        # Override settings
        if target:
            test_config.targets = [TargetConfig.from_dict(target)]

        test_config.parallel = parallel
        test_config.maxWorkers = workers
        test_config.cache.enabled = cache
        test_config.output.formats = list(output_format)
        test_config.output.dir = output
        if strict:
            test_config.validate()
        else:
            _coerce_non_strict_config(test_config)

    except FileNotFoundError as e:
        click.echo(f"Error: Configuration file not found: {e}", err=True)
        sys.exit(1)
    except ValueError as e:
        click.echo(f"Error: Invalid configuration: {e}", err=True)
        sys.exit(1)

    # Resolve effective thresholds.
    effective_block_threshold = (
        float(threshold)
        if threshold is not None
        else float(test_config.thresholds.get("block_rate", 0.8))
    )
    if not 0.0 <= effective_block_threshold <= 1.0:
        click.echo(
            f"Error: block rate threshold must be in [0.0, 1.0], got {effective_block_threshold}",
            err=True,
        )
        sys.exit(1)

    effective_critical_threshold = None
    if "critical_block_rate" in test_config.thresholds:
        effective_critical_threshold = float(test_config.thresholds["critical_block_rate"])
        if not 0.0 <= effective_critical_threshold <= 1.0:
            click.echo(
                "Error: critical_block_rate threshold must be in [0.0, 1.0], "
                f"got {effective_critical_threshold}",
                err=True,
            )
            sys.exit(1)

    # Validate targets
    if not test_config.targets:
        click.echo("Error: No target specified. Use --target or add targets to config.", err=True)
        sys.exit(1)
    if not test_config.plugins:
        click.echo("Error: No valid plugins configured after normalization.", err=True)
        sys.exit(1)

    # Create target
    target_config = test_config.targets[0]
    try:
        from ..testing.targets import GuardrailTarget, MockTarget

        if target_config.type == "mock":
            test_target = MockTarget()
        elif target_config.type == "guardrail":
            from ..guardrail import guardrail
            guardrail_fn = getattr(guardrail, target_config.url, None)
            if guardrail_fn is None:
                click.echo(f"Error: Guardrail '{target_config.url}' not found", err=True)
                sys.exit(1)
            test_target = GuardrailTarget(guardrail_fn=guardrail_fn)
        elif target_config.type == "http":
            test_target = _create_http_target(target_config)
        else:
            click.echo(
                f"Error: Unsupported target type '{target_config.type}'. "
                "Supported: http, guardrail, mock",
                err=True,
            )
            sys.exit(1)
    except Exception as e:
        click.echo(f"Error creating target: {e}", err=True)
        sys.exit(1)

    # Create cache
    llm_cache = None
    if test_config.cache.enabled:
        llm_cache = LLMCallCache(
            cache_dir=test_config.cache.dir,
            ttl_seconds=test_config.cache.ttl,
        )

    # Create runner
    runner = ConcurrentTestRunner(test_config, cache=llm_cache)

    # Progress callback
    def on_progress(progress: RunProgress):
        if verbose:
            click.echo(
                f"\rProgress: {progress.completed}/{progress.total} "
                f"({progress.percent_complete:.1f}%) "
                f"Block rate: {progress.block_rate:.1%} "
                f"[{progress.current_plugin}]",
                nl=False,
            )

    # Run tests
    click.echo("Running security tests...")
    click.echo(f"  Target: {target_config.to_target_string()}")
    click.echo(f"  Plugins: {len(test_config.plugins)}")
    click.echo(f"  Strategies: {len(test_config.strategies)}")
    click.echo(f"  Parallel: {test_config.parallel} (workers: {test_config.maxWorkers})")
    click.echo(f"  Cache: {'enabled' if test_config.cache.enabled else 'disabled'}")
    click.echo(f"  Block threshold: {effective_block_threshold:.1%}")
    if effective_critical_threshold is not None:
        click.echo(f"  Critical threshold: {effective_critical_threshold:.1%}")
    click.echo()

    try:
        summary = runner.run(test_target, on_progress=on_progress if verbose else None)
    except Exception as e:
        click.echo(f"\nError during test execution: {e}", err=True)
        if verbose:
            import traceback
            click.echo(traceback.format_exc(), err=True)
        sys.exit(2)

    # Clear progress line
    if verbose:
        click.echo()

    # Display results
    click.echo("\n" + "=" * 60)
    click.echo("SECURITY TEST RESULTS")
    click.echo("=" * 60)

    click.echo(f"\nTotal Tests: {summary.total_tests}")
    click.echo(f"Blocked Attacks: {summary.blocked_attacks}")
    click.echo(f"Successful Attacks: {summary.successful_attacks}")
    click.echo(f"Errors: {summary.errors}")
    click.echo(f"\nBlock Rate: {summary.block_rate:.1%}")
    click.echo(f"Attack Success Rate: {summary.attack_success_rate:.1%}")
    click.echo(f"Execution Time: {summary.total_time_seconds:.2f}s")

    if test_config.cache.enabled:
        click.echo(f"\nCache Hit Rate: {summary.cache_hit_rate:.1%}")
        click.echo(f"Cost Saved: ${summary.cost_saved:.4f}")

    # Display vulnerabilities
    if summary.vulnerabilities:
        click.echo(f"\n{'!' * 60}")
        click.echo(f"VULNERABILITIES FOUND: {len(summary.vulnerabilities)}")
        click.echo(f"{'!' * 60}")

        for vuln in summary.vulnerabilities[:10]:
            severity = vuln.payload.severity.value if hasattr(vuln.payload.severity, 'value') else str(vuln.payload.severity)
            click.echo(f"\n  [{severity.upper()}] {vuln.payload.id}")
            click.echo(f"    Technique: {vuln.payload.technique}")
            prompt_preview = vuln.payload.prompt[:80] + "..." if len(vuln.payload.prompt) > 80 else vuln.payload.prompt
            click.echo(f"    Payload: {prompt_preview}")

        if len(summary.vulnerabilities) > 10:
            click.echo(f"\n  ... and {len(summary.vulnerabilities) - 10} more")

    # Critical-only block rate (if critical payloads exist).
    critical_results = [
        r
        for r in summary.results
        if (
            r.payload.severity.value
            if hasattr(r.payload.severity, "value")
            else str(r.payload.severity)
        ).lower()
        == "critical"
    ]
    critical_total = len(critical_results)
    critical_blocked = sum(1 for r in critical_results if r.blocked)
    critical_block_rate = (
        critical_blocked / critical_total if critical_total > 0 else 1.0
    )
    if critical_total > 0:
        click.echo(
            f"\nCritical Block Rate: {critical_block_rate:.1%} "
            f"({critical_blocked}/{critical_total})"
        )

    # Save results
    output_dir = Path(output)
    output_dir.mkdir(parents=True, exist_ok=True)
    result_payload = summary.to_dict()
    result_payload["thresholds"] = test_config.thresholds
    result_payload["effective_thresholds"] = {
        "block_rate": effective_block_threshold,
        **(
            {"critical_block_rate": effective_critical_threshold}
            if effective_critical_threshold is not None
            else {}
        ),
    }
    result_payload["critical_block_rate"] = critical_block_rate
    result_payload["critical_totals"] = {
        "total": critical_total,
        "blocked": critical_blocked,
    }

    if "json" in output_format:
        json_path = output_dir / "results.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(result_payload, f, indent=2)
        click.echo(f"\nJSON results saved to: {json_path}")

    if "html" in output_format:
        html_path = output_dir / "results.html"
        _save_html_report(summary, html_path)
        click.echo(f"HTML report saved to: {html_path}")

    # Check threshold
    passed = summary.block_rate >= effective_block_threshold
    threshold_messages = [
        "block rate "
        f"{summary.block_rate:.1%} "
        f"{'>=' if summary.block_rate >= effective_block_threshold else '<'} "
        f"{effective_block_threshold:.1%}"
    ]
    if effective_critical_threshold is not None:
        critical_pass = critical_block_rate >= effective_critical_threshold
        passed = passed and critical_pass
        threshold_messages.append(
            "critical block rate "
            f"{critical_block_rate:.1%} "
            f"{'>=' if critical_pass else '<'} "
            f"{effective_critical_threshold:.1%}"
        )

    click.echo(f"\n{'=' * 60}")
    if passed:
        click.echo(f"PASSED - {'; '.join(threshold_messages)}")
        sys.exit(0)
    else:
        click.echo(f"FAILED - {'; '.join(threshold_messages)}")
        sys.exit(1)


# =============================================================================
# CI Command Group
# =============================================================================

@click.group()
def ci():
    """CI/CD integration commands.

    Generate workflows and check results for continuous integration.
    """
    pass


@ci.command()
@click.option(
    "--provider",
    "-p",
    type=click.Choice(["github", "gitlab", "jenkins"]),
    default="github",
    help="CI provider",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    help="Output path (default: auto-detect)",
)
@click.option(
    "--config",
    "-c",
    default="promptfoo.yaml",
    help="Path to promptfoo config file to use",
)
@click.option(
    "--threshold",
    default=0.8,
    type=float,
    help="Block rate threshold",
)
def generate(provider: str, output: str | None, config: str, threshold: float):
    """Generate CI/CD workflow configuration.

    \b
    Examples:
        dspy-guardrails ci generate --provider github
        dspy-guardrails ci generate -p gitlab -o .gitlab-ci.yml
    """
    from ..testing.ci import generate_workflow

    try:
        workflow = generate_workflow(
            provider=provider,
            config_path=config,
            threshold=threshold,
        )

        # Determine output path
        if output is None:
            if provider == "github":
                output = ".github/workflows/security-scan.yml"
            elif provider == "gitlab":
                output = ".gitlab-ci.yml"
            elif provider == "jenkins":
                output = "Jenkinsfile"

        # Create directories
        output_path = Path(output)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Write workflow
        with open(output_path, "w") as f:
            f.write(workflow)

        click.echo(f"CI workflow generated: {output_path}")
        click.echo(f"  Provider: {provider}")
        click.echo(f"  Config: {config}")
        click.echo(f"  Threshold: {threshold:.0%}")

    except Exception as e:
        click.echo(f"Error generating workflow: {e}", err=True)
        sys.exit(1)


@ci.command()
@click.option(
    "--results",
    "-r",
    type=click.Path(exists=True),
    required=True,
    help="Path to results JSON file",
)
@click.option(
    "--threshold",
    default=0.8,
    type=float,
    help="Block rate threshold (0.0-1.0)",
)
@click.option(
    "--format",
    "-f",
    type=click.Choice(["text", "json", "github"]),
    default="text",
    help="Output format",
)
def check(results: str, threshold: float, format: str):
    """Check test results against threshold.

    Exits with code 0 if passed, 1 if failed.

    \b
    Examples:
        dspy-guardrails ci check --results results.json --threshold 0.8
        dspy-guardrails ci check -r results.json -f github
    """
    try:
        with open(results) as f:
            data = json.load(f)

        # Extract block rate
        block_rate_str = data.get("block_rate", "0%")
        if isinstance(block_rate_str, str):
            block_rate = float(block_rate_str.rstrip("%")) / 100
        else:
            block_rate = float(block_rate_str)

        passed = block_rate >= threshold

        if format == "json":
            output = {
                "passed": passed,
                "block_rate": block_rate,
                "threshold": threshold,
                "vulnerabilities": len(data.get("vulnerabilities", [])),
            }
            click.echo(json.dumps(output, indent=2))

        elif format == "github":
            # GitHub Actions output format
            click.echo(f"::set-output name=passed::{str(passed).lower()}")
            click.echo(f"::set-output name=block_rate::{block_rate:.2%}")
            if not passed:
                click.echo(f"::error::Security check failed. Block rate {block_rate:.1%} < {threshold:.1%}")

        else:
            click.echo(f"Block Rate: {block_rate:.1%}")
            click.echo(f"Threshold: {threshold:.1%}")
            click.echo(f"Status: {'PASSED' if passed else 'FAILED'}")

            if data.get("vulnerabilities"):
                click.echo(f"Vulnerabilities: {len(data['vulnerabilities'])}")

        sys.exit(0 if passed else 1)

    except FileNotFoundError:
        click.echo(f"Error: Results file not found: {results}", err=True)
        sys.exit(2)
    except json.JSONDecodeError:
        click.echo("Error: Invalid JSON in results file", err=True)
        sys.exit(2)
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(2)


# =============================================================================
# Register with main CLI
# =============================================================================

def register_commands(cli_group):
    """Register promptfoo commands with the main CLI group.

    Args:
        cli_group: Click group to register with
    """
    cli_group.add_command(redteam)
    cli_group.add_command(ci)
